services:
  mysql:
    image: mysql:9.2.0
    container_name: munchies-mysql
    env_file: mysql.env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - munchies

  mysql-keycloak:
    image: mysql:9.2.0
    container_name: munchies-mysql-keycloak
    env_file: mysql-keycloak.env
    ports:
      - 3307:3306
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    networks:
      - munchies

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: munchies-keycloak
    command: start-dev --import-realm
    env_file: keycloak.env
    ports:
      - 8080:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - mysql-keycloak
    networks:
      - munchies

  minio:
    image: minio/minio
    container_name: munchies-minio
    command: server --console-address ":9001" /data
    env_file: minio.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    networks:
      - munchies

  redis:
    image: redis:8.2.3-alpine
    container_name: munchies-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - munchies

  node-exporter:
    image: prom/node-exporter:latest
    container_name: munchies-node-exporter
    ports:
      - 9100:9100
    networks:
      - munchies

  prometheus:
    image: prom/prometheus:latest
    container_name: munchies-prometheus
    command:
      - "--storage.tsdb.retention.time=15d"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter
    networks:
      - munchies

  grafana:
    image: grafana/grafana:latest
    container_name: munchies-grafana
    env_file:
      - mysql.env
      - grafana.env
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - mysql
      - prometheus
    networks:
      - munchies

  file:
    image: munchies/file:1.0.0
    container_name: munchies-file
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - 4002:4002
    depends_on:
      - minio
    networks:
      - munchies

  recipe:
    image: munchies/recipe:7.0.0
    container_name: munchies-recipe
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - 4001:4001
    depends_on:
      - mysql
      - keycloak
      - redis
      - file
    networks:
      - munchies

  gateway:
    image: munchies/gateway:2.1.0
    container_name: munchies-gateway
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - 4000:4000
    depends_on:
      - mysql
      - keycloak
      - minio
      - redis
      - recipe
    networks:
      - munchies

volumes:
  mysql_data:
  mysql_keycloak_data:
  minio_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  munchies:
    name: munchies
    driver: bridge
