services:
  mysql:
    image: mysql:9.2.0
    container_name: munchies-mysql
    environment:
      MYSQL_DATABASE: ${DB_MAIN_DB}
      MYSQL_USER: ${DB_MAIN_USERNAME}
      MYSQL_PASSWORD: ${DB_MAIN_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MAIN_ROOT_PASSWORD}
    ports:
      - ${DB_MAIN_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - munchies

  mysql-keycloak:
    image: mysql:9.2.0
    container_name: munchies-mysql-keycloak
    environment:
      MYSQL_DATABASE: ${DB_KEYCLOAK_DB}
      MYSQL_USER: ${DB_KEYCLOAK_USERNAME}
      MYSQL_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_KEYCLOAK_ROOT_PASSWORD}
    ports:
      - ${DB_KEYCLOAK_PORT}:3306
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    networks:
      - munchies

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: munchies-keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-keycloak:3306/${DB_KEYCLOAK_DB}
      KC_DB_USERNAME: ${DB_KEYCLOAK_USERNAME}
      KC_DB_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: false
    ports:
      - ${KEYCLOAK_PORT}:8080
    command:
      - start-dev
    networks:
      - munchies
    depends_on:
      - mysql-keycloak

  minio:
    image: minio/minio
    container_name: munchies-minio
    ports:
      - ${S3_PORT}:9000
      - ${S3_WEB_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":${S3_WEB_PORT}" /data
    networks:
      - munchies

  redis:
    image: redis:8.2.3-alpine
    container_name: munchies-redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    networks:
      - munchies

  recipe:
    image: munchies/recipe:5.0.0
    container_name: munchies-recipe
    build:
      context: .
      dockerfile: recipe/Dockerfile
    ports:
      - ${APP_RECIPE_PORT}:4001
    environment:
      SPRING_PROFILES_ACTIVE: stage
    depends_on:
      - mysql
      - keycloak
      - minio
      - redis
    networks:
      - munchies

  gateway:
    image: munchies/gateway:1.0.0
    container_name: munchies-gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - ${APP_GATEWAY_PORT}:4000
    environment:
      SPRING_PROFILES_ACTIVE: stage
    depends_on:
      - mysql
      - keycloak
      - minio
      - redis
      - recipe
    networks:
      - munchies

volumes:
  mysql_data:
  mysql_keycloak_data:
  minio_data:
  redis_data:

networks:
  munchies:
    name: munchies
    driver: bridge
