services:
  mysql:
    image: mysql:9.2.0
    container_name: munchies-mysql
    environment:
      MYSQL_DATABASE: ${DB_MAIN_DB}
      MYSQL_USER: ${DB_MAIN_USERNAME}
      MYSQL_PASSWORD: ${DB_MAIN_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MAIN_ROOT_PASSWORD}
    ports:
      - ${DB_MAIN_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - munchies

  mysql-keycloak:
    image: mysql:9.2.0
    container_name: munchies-mysql-keycloak
    environment:
      MYSQL_DATABASE: ${DB_KEYCLOAK_DB}
      MYSQL_USER: ${DB_KEYCLOAK_USERNAME}
      MYSQL_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_KEYCLOAK_ROOT_PASSWORD}
    ports:
      - ${DB_KEYCLOAK_PORT}:3306
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    networks:
      - munchies

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: munchies-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-keycloak:3306/${DB_KEYCLOAK_DB}
      KC_DB_USERNAME: ${DB_KEYCLOAK_USERNAME}
      KC_DB_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: false
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - mysql-keycloak
    networks:
      - munchies

  minio:
    image: minio/minio
    container_name: munchies-minio
    command: server --console-address ":${S3_WEB_PORT}" /data
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    ports:
      - ${S3_PORT}:9000
      - ${S3_WEB_PORT}:9001
    volumes:
      - minio_data:/data
    networks:
      - munchies

  redis:
    image: redis:8.2.3-alpine
    container_name: munchies-redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    networks:
      - munchies

  node-exporter:
    image: prom/node-exporter:latest
    container_name: munchies-node-exporter
    ports:
      - ${NODE_EXPORTER_PORT}:9100
    networks:
      - munchies

  prometheus:
    image: prom/prometheus:latest
    container_name: munchies-prometheus
    command:
      - "--storage.tsdb.retention.time=15d"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - prometheus_data:/prometheus
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on: node-exporter
    networks:
      - munchies

  grafana:
    image: grafana/grafana:latest
    container_name: munchies-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      DB_MAIN_DB: ${DB_MAIN_DB}
      DB_MAIN_USERNAME: ${DB_MAIN_USERNAME}
      DB_MAIN_PASSWORD: ${DB_MAIN_PASSWORD}
      DB_MAIN_PORT: ${DB_MAIN_PORT}
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - mysql
      - prometheus
    networks:
      - munchies

  file:
    image: munchies/file:1.0.0
    container_name: munchies-file
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - ${APP_FILE_PORT}:4002
    depends_on: minio
    networks:
      - munchies

  recipe:
    image: munchies/recipe:7.0.0
    container_name: munchies-recipe
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - ${APP_RECIPE_PORT}:4001
    depends_on:
      - mysql
      - keycloak
      - redis
      - file
    networks:
      - munchies

  gateway:
    image: munchies/gateway:2.1.0
    container_name: munchies-gateway
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - ${APP_GATEWAY_PORT}:4000
    depends_on:
      - mysql
      - keycloak
      - minio
      - redis
      - recipe
    networks:
      - munchies

volumes:
  mysql_data:
  mysql_keycloak_data:
  minio_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  munchies:
    name: munchies
    driver: bridge
