apiVersion: 1

datasources:
  - name: munchies
    uid: df95d61129vy8b
    type: mysql
    url: mysql:3306
    user: ${MYSQL_USER}
    access: proxy
    jsonData:
      database: ${MYSQL_DATABASE}
      sslmode: disable
    secureJsonData:
      password: ${MYSQL_PASSWORD}
  - name: prometheus
    uid: ef98vg6y97da8a
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    jsonData:
      httpMethod: GET
