spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: keycloak
              uri: http://localhost:8080
              predicates:
                - Path=/auth/login
              filters:
                - RewritePath=/auth/login,/realms/munchies/protocol/openid-connect/token
            - id: recipe-service
              uri: http://localhost:4001
              predicates:
                - Path=/recipes/**, /labels/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@tokenKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/munchies
