server:
  port: 4001
  servlet.context-path: /api

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: recipe-service
          uri: http://localhost:4000
          predicates:
            - Path=/api/v1/recipes/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/munchies