server:
  port: 4000

spring:
  application:
    name: munchies-gateway
  cloud:
    gateway:
      routes:
        - id: recipe-service
          uri: http://localhost:4001
          predicates:
            - Path=/api/v1/recipes/**, /api/v1/labels/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/munchies