server:
  port: 4000

spring:
  application:
    name: munchies-gateway
  cloud:
    gateway:
      routes:
        - id: recipe-service
          uri: http://localhost:4001
          predicates:
            - Path=/v1/recipes/**, /v1/labels/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@tokenKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/munchies
