server:
  port: 4001

spring:
  r2dbc:
    initialization-mode: never
    url: r2dbc:mysql://mysql:3306/munchies
    username: admin
    password: admin
  flyway:
    url: jdbc:mysql://localhost:3306/munchies
    user: admin
    password: admin
    enabled: true
    baselineOnMigrate: true
  s3:
    endpoint-override: http://minio:9000
    path-style-access: true
    aws:
      region: us-east-1
      credentials:
        type: static
        static-provider:
          access-key-id: adminadmin
          secret-access-key: adminadmin

springdoc.api-docs.path: /docs