server:
  port: 4001

spring:
  r2dbc:
    initialization-mode: never
    url: r2dbc:mysql://mysql:3306/munchies
    username: admin
    password: admin
  flyway:
    url: jdbc:mysql://mysql:3306/munchies
    user: admin
    password: admin
    enabled: true
    baselineOnMigrate: true

services:
  file:
    url: http://file:4002

springdoc.api-docs.path: /docs
