server:
  port: 4001

spring:
  r2dbc:
    initialization-mode: never
    url: r2dbc:mysql://mysql:3306/munchies
    username: admin
    password: admin
  flyway:
    url: jdbc:mysql://localhost:3306/munchies
    user: admin
    password: admin
    enabled: true
    baselineOnMigrate: true

springdoc.api-docs.path: /docs
